import { generatePipelineCode } from '@/engine/codegen';
import type { Workflow } from '@/lib/types';
import { sanitizeCommentLine } from '@/lib/utils';

export type ScriptWorkflow = Pick<Workflow, 'nodes' | 'edges' | 'params' | 'name' | 'createdAt' | 'updatedAt'>;

export function generatePythonScript(workflow: ScriptWorkflow): string {
  const header = [
    '# Generated by Transform Studio',
    `# Workflow: ${sanitizeCommentLine(workflow.name)}`,
    `# Created: ${sanitizeCommentLine(workflow.createdAt)}`,
    `# Updated: ${sanitizeCommentLine(workflow.updatedAt)}`,
    '#',
    '# Adjust source file paths before running in your environment.',
    '',
  ];

  return [...header, generatePipelineCode(workflow)].join('\n');
}

export function downloadPythonScript(
  workflow: ScriptWorkflow,
  filename = 'pipeline.py',
): void {
  const content = generatePythonScript(workflow);
  const blob = new Blob([content], { type: 'text/x-python' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export { generatePipelineCode };
