import { describe, expect, it } from 'vitest';

import { generatePipelineCode } from '@/engine/codegen';
import { generatePythonScript } from '@/export/python-script';
import type { Workflow } from '@/lib/types';

const workflow: Workflow = {
  id: 'wf1',
  name: 'Sales pipeline',
  schemaVersion: 1,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-06-14T12:00:00Z',
  params: [{ name: 'country', type: 'string', default: 'US' }],
  nodes: [
    {
      id: 'src',
      type: 'source.csv',
      position: { x: 0, y: 0 },
      config: { filename: 'sales.csv', delimiter: ',', header: true, encoding: 'utf-8' },
    },
    {
      id: 'flt',
      type: 'filter',
      position: { x: 0, y: 0 },
      config: { expression: 'df["country"] == params[\'country\']' },
    },
  ],
  edges: [{ id: 'e1', source: 'src', target: 'flt' }],
};

describe('generatePythonScript', () => {
  it('includes header comment block with workflow metadata', () => {
    const script = generatePythonScript(workflow);

    expect(script).toMatch(/^# Generated by Transform Studio/);
    expect(script).toContain('# Workflow: Sales pipeline');
    expect(script).toContain('# Created: 2026-01-01T00:00:00Z');
    expect(script).toContain('# Updated: 2026-06-14T12:00:00Z');
    expect(script).toContain('Adjust source file paths');
  });

  it('sanitizes newlines in workflow name for comment safety', () => {
    const malicious: Workflow = {
      ...workflow,
      name: 'Evil\nimport os; os.system("rm -rf /")',
    };
    const script = generatePythonScript(malicious);

    expect(script).toContain('# Workflow: Evil import os; os.system("rm -rf /")');
    expect(script).not.toMatch(/^import os/m);
  });

  it('includes imports, params, and per-node section comments', () => {
    const script = generatePythonScript(workflow);
    const pipeline = generatePipelineCode(workflow);

    expect(script).toContain(pipeline);
    expect(script).toContain('import pandas as pd');
    expect(script).toContain('params = {');
    expect(script).toContain('# CSV Source');
    expect(script).toContain('# Node ID: src');
    expect(script).toContain('# Type: source.csv');
    expect(script).toContain('# Source file: sales.csv');
    expect(script).toContain('# Filter');
    expect(script).toContain('pd.read_csv');
  });
});
